coverage:
  precision: 2
  round: down
  range: "80...100"

ignore:
  - "tests/"
  - "docs/"

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
